name = "DictionarySlicing"
uuid = "a912d89d-ef62-4f6b-8cba-1b09a150679e"
authors = ["Dan Kool"]
version = "0.5.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
