name = "DictionarySlicing"
uuid = "a912d89d-ef62-4f6b-8cba-1b09a150679e"
authors = ["Dan Kool"]
version = "0.6.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
OrderedCollections = "1"
Reexport = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
